!include pymodule.yaml
---
- package: Keras_Applications 
  name: Keras_Applications
  version: "{{ versions.keras_applications }}"
  pypiurl: https://files.pythonhosted.org/packages/21/56/4bcec5a8d9503a87e58e814c4e32ac2b32c37c685672c30bc8c54c6e478a
  description: |
    Keras Applications is the applications module of the Keras deep learning library. 
    It provides model definitions and pre-trained weights for a number of popular archictures, 
    such as VGG16, ResNet50, Xception, MobileNet, and more
