!include pymodule.yaml
---
- package: Keras Applications
  name: keras-applications
  version: "{{versions.keras_applications}}"
  vendor_source: https://github.com/keras-team/keras-applications/archive/{{version}}.{{extension}}
  description: |
    Keras Applications is the applications module of the Keras deep learning library.
    It provides model definitions and pre-trained weights for a number of popular
    archictures, such as VGG16, ResNet50, Xception, MobileNet, and more
